// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
	export interface StyleCss {
		status: string;
	}
}

declare const StyleCssModule: StyleCssNamespace.StyleCss;

export = StyleCssModule;
